matrix: 
  include:
    - language: node_js
      node_js:
        - "12.18.2"
      install:
        - npm install
      script:
        - ng test --watch=false

    # - language: java
    #   jdk: oraclejdk8
    #   script:
    #     - mvn test -B


cache: npm

services:
  - docker

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: 
#     secure:
#   secret_access_key: 
#     secure:
#   region: "us-east-1"
#   app: "Project2"
#   env: "Project2-env"
#   bucket_name: "WoodenWindow"
